### ISSUE TITLE
User: Delete user doesn't work

### ISSUE THREAD

**Issue by opmanual** [SanDiegoHanbitChurch/hanbit-manager#95]
Steps to reproduce

1. Login
2. Click on "사용자" menu
3. Press Delete button to delete user

Expected result: User should be deleted

Actual result: 
![image](https://user-images.githubusercontent.com/14799195/75577876-bb385400-5a17-11ea-8bcb-8e4f0a47c521.png)

**Comment by sangyum** [comment]
fixed
